import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen flex justify-center items-center bg-gradient-to-r from-gray-100 to-gray-200">
        <article className="flex flex-col rounded-lg shadow-2xl bg-gradient-to-br from-gray-700 to-gray-800 m-8 text-white p-8 w-1/4 h-1/4 transform transition-all duration-500 hover:scale-105">
          <h1 className="text-2xl font-bold mb-4 text-center">
            Welcome to Our Platform
          </h1>
          <div className="flex flex-col gap-4 justify-center items-center h-full">
            <Link href="login">
              <button className="transition-all duration-300 ease-in-out transform hover:scale-105 rounded-md bg-gradient-to-r from-blue-600 to-blue-700 px-5 py-2 text-white hover:from-blue-500 hover:to-blue-600 shadow-md">
                Login
              </button>
            </Link>

            <p className="text-gray-400 text-lg">or</p>

            <Link href="signup">
              <button className="transition-all duration-300 ease-in-out transform hover:scale-105 rounded-md bg-gradient-to-r from-purple-600 to-purple-700 px-5 py-2 text-white hover:from-purple-500 hover:to-purple-600 shadow-md">
                Sign Up
              </button>
            </Link>
          </div>
        </article>
      </div>
    </>
  );
}
